### PR TITLE
added tutorial about solution set characterization

### LINKED ISSUE #37: Add examples from GSoC blog to documentation
The [first GSoC blogpost](https://lucaferranti.github.io/posts/2021/06/gsoc_blog1/) is a good example to put in the documentation.  I think in the current form the current blog should go under explanations. However I can adapt a subset of it to make also a tutorial.

### PR DESCRIPTION
**Pull request by lucaferranti**
added tutorial/explanation about Oettli-Präger theorem, similar to first gsoc blog

fixes #37

### CODE REVIEW

**Review by mforets — APPROVED** [review]
very nice write up :100:

**Comment by lucaferranti** [comment]
the CI for the documentation is failing though. The error says "segmentation fault", is the code to computational intensive?

**Comment by lucaferranti** [comment]
strange though, it builds in seconds on my pc locally 🤔

**Comment by lucaferranti** [comment]
now it works, it seems the problem was the missing Manifest.toml from the docs?

**Pull request merged**
