### PR TITLE
Fix complex matrix multiplication

### LINKED ISSUE #85: [bug]: issues with complex interval matrices multiplication
## Bug description
At the moment, using complex interval matrices falls back to the "default" multiplication in LinearAlgebra.jl instead of using Rump fast multiplication, which should be added for complex interval matrices.

## Minimum (non-)working example

```julia
julia> typeof(A)
Matrix{Complex{Interval{Float64}}} (alias for Array{Complex{Interval{Float64}}, 2})

julia> @which A * A
*(A::AbstractMatrix{T} where T, B::AbstractMatrix{T} where T) in LinearAlgebra at C:\Users\lucaa\AppData\Local\Programs\Julia-1.6.1\share\julia\stdlib\v1.6\LinearAlgebra\src\matmul.jl:151

julia> typeof(P)
Matrix{Interval{Float64}} (alias for Array{Interval{Float64}, 2})

julia> typeof(D)
Diagonal{ComplexF64, Vector{ComplexF64}}

julia> P * D
ERROR: MethodError: no method matching *(::IntervalLinearAlgebra.MultiplicationType{:fast}, ::Matrix{Interval{Float64}})
Closest candidates are:
  *(::IntervalLinearAlgebra.MultiplicationType{:fast}, ::AbstractArray{Interval{T}, 2}, ::AbstractArray{Interval{T}, 2}) where T<:Real at c:\Users\lucaa\projects\IntervalLinearAlgebra\src\multiplication.jl:46
  *(::IntervalLinearAlgebra.MultiplicationType{:fast}, ::AbstractArray{Interval{T}, 2}, ::AbstractMatrix{T}) where T<:Real at c:\Users\lucaa\projects\IntervalLinearAlgebra\src\multiplication.jl:101
  *(::IntervalLinearAlgebra.MultiplicationType{:fast}, ::AbstractMatrix{T}, ::AbstractArray{Interval{T}, 2}) where T<:Real at c:\Users\lucaa\projects\IntervalLinearAlgebra\src\multiplication.jl:76
  ...
Stacktrace:
 [1] *(::IntervalLinearAlgebra.MultiplicationType{:fast}, ::Matrix{Interval{Float64}}, ::Diagonal{ComplexF64, Vector{ComplexF64}})
   @ Base .\operators.jl:560
 [2] *(A::Matrix{Interval{Float64}}, B::Diagonal{ComplexF64, Vector{ComplexF64}})
   @ IntervalLinearAlgebra c:\Users\lucaa\projects\IntervalLinearAlgebra\src\multiplication.jl:37
 [3] top-level scope
   @ REPL[86]:1
```

## Expected behavior

should use the multiplication algorithm defined in the package.

## Related issues

- #72 

## Additional information

I am starting to think I should define a `IntervalMatrix` type here and define the operations on it, this would solve this, #72 and other possible issues that haven't noticed yet.

### PR DESCRIPTION
**Pull request by orkolorko**
## PR description
We define new methods so that multiplication with complex interval matrices is correctly dispatched

## Before 
The compiler dispatched to the slow multiplication method

## After
The matrix product with complex matrices is dispatched correctly and uses the multiplication function exported by IntervalLinearAlgebra

## Checklist

- [X] Updated/added tests

### CODE REVIEW

**Comment by orkolorko** [comment]
I know that it is not an optimal solution; as we already discussed, the best line of work would be to define a new type with midpoint-radius matrices (and then store the real and imaginary part as two of these matrices), but this is a temporary fix.

**Comment by lucaferranti** [comment]
Indeed, to avoid ambiguities and type piracy we want a dedicated type. This fix definitely does not hurt though, so it's very welcome

**Comment by lucaferranti** [comment]
btw @orkolorko, feel free to send me a message on the julia slack or zulip (I am Luca Ferranti on both and same profile picture of github).

We could have a short video chat to discuss future directions of IntervalLinearAlgebra.jl (dont take this as an expectation of commitment, I'd simply be interested in hearing more what you are using the package for and how I can help you in the development)

**Comment by lucaferranti** [comment]
this will probably become outdated once we introduce `MidRadMatrix`, but for now it's good to have

**Review by lucaferranti — APPROVED** [review]

**Pull request merged**
